# Site settings
title: 李小胖&Julia
email: hustneverland@163.com
description: > # this means to ignore newlines until "baseurl:"
  爱julia、爱生活、爱技术。
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  hustneverland

# Build settings
markdown: kramdown

